module.exports = {
  EVENT: {
    CONNECTION_SUCCESS: "connection-success",
    JOIN_ROOM: "join-room",
    JOIN_ROOM_CALLBACK: "join-room-callback",
    CREATE_WEB_RTC_TRANSPORT: "create-web-rtc-transport",
    CREATE_WEB_RTC_TRANSPORT_CALLBACK: "create-web-rtc-transport-callback",
    GET_PRODUCERS: "get-proucers",
    GET_PRODUCERS_CALLBACK: "get-producers-callback",
    TRANSPORT_CONNECT: "transport-connect",
    TRANSPORT_CONNECT_CALLBACK: "transport-connect-callback",
    TRANSPORT_PRODUCE: "transport-produce",
    TRANSPORT_PRODUCE_CALLBACK: "transport-produce-callback",
    TRANSPORT_RECV_CONNECT: "transport-recv-connect",
    CONSUME: "consume",
    CONSUME_CALLBACK: "consume-callback",
    RESUME: "resume",
    WEB_RTC_TRANPORT_CONSUMER_CALLBACK: "web-rtc-consumer-callback",
    PRODUCER_CLOSED: "producer-closed",
    NEW_PRODUCER: "new-producer",
    CONSUMER_RESUME: "consumer-resume",
  },
};
// module.exports = {
//   EVENT: {
//     CONNECTION_SUCCESS: "connection-success",
//     DISCONNECT: "disconnect",
//     GET_RTP_CAPABILITIES: "getRtpCapabilities",
//     ON_RTP_CAPABILITIES: "onRtpCapabilities",
//     CREATE_WEBRTC_TRANSPORT: "createWebRtcTransport",
//     CREATE_RECV_TRANSPORT: "createRecvRtcTransport",
//     ON_WEBRTC_TRANSPORT: "onWebRtcTransport",
//     TRANSPORT_CONNECT: "transportConnect",
//     TRANSPORT_PRODUCE: "transportProduce",
//     TRANSPORT_RECV_CONNECT: "transportRecvConnect",
//     CONSUME: "consume",
//     CONSUME_CALLBACK: "consume-callback",
//     CONSUMER_RESUME: "consumerResume",
//   },
// };
